bind_ip: 192.168.16.151
port: 50021
thread_pool_size: 4
pass_via: no
via_svc: 192.168.16.153:50041
code_root_dir: contract_work_dir
results_root_dir: results_root
schedule_svc: 192.168.16.151:51131
