bind_ip: 127.0.0.1
port: 50021
task_port_range: [41000, 41100]
thread_pool_size: 12
pass_via: true
code_root_dir: contract_work_dir
results_root_dir: results_root
total_bandwidth: 20000000
channel_log_level: 2
certs: 
  base_path: ../certs
  root_cert: CA.crt
  server_sign_key: SS.key
  server_sign_cert: SS.crt
  server_enc_key: SE.key
  server_enc_cert: SE.crt
  client_sign_key: CS.key
  client_sign_cert: CS.crt
  client_enc_key: CE.key
  client_enc_cert: CE.crt
consul:
  service_ip: 127.0.0.1
  service_port: 8500
  name: jobService
  tag: job
  interval: 3s
  deregister: 3s
