bind_ip: 0.0.0.0
port: 50021
ice_grid: 192.168.2.128:10032 # Use this parameter when not using consul
task_port_range: [41000, 41100]
thread_pool_size: 12
pass_ice: true
code_root_dir: contract_work_dir
results_root_dir: results_root
total_bandwidth: 100000000
channel_log_level: 2
certs: 
  base_path: ""
  root_cert: ""
  cert_dir: ""
  server_cert: SS.key
  client_cert: CC.key
  password: 123456
consul:
  service_ip: 0.0.0.0
  service_port: 8500
  name: jobService
  tag: job
  interval: 3s
  deregister: 3s
