data_root: ../data
file_system: local
bind_ip: 192.168.16.151
port: 50011
chunk_size: 1024
pass_via: yes
via_svc: 192.168.16.153:50041
thread_pool_size: 4
code_root_dir: ../contract_work_dir
results_root_dir: results_root
