bind_ip: 0.0.0.0
register_ip: 127.0.0.1
port: 50021
ice_grid: 127.0.0.1:55559 # Use this parameter when not using consul
task_port_range: [31000, 31100]
file_system: local
chunk_size: 1024
pass_ice: true
thread_pool_size: 12
data_root: ../data
code_root_dir: algorithm_work_dir
results_root_dir: results_root
total_bandwidth: 100000000
certs:
  base_path: ""
  root_cert: ""
  cert_dir: ""
  server_cert: SS.key
  client_cert: CC.key
  password: 123456
consul:
  service_ip: 0.0.0.0
  service_port: 8500
  name: dataService
  tag: data
  interval: 3s
  deregister: 3s
