file_system: local
bind_ip: 192.168.16.151
port: 50011
chunk_size: 1024
pass_via: yes
via_svc: 192.168.16.153:50041
thread_pool_size: 4
data_root: ../data
code_root_dir: ../contract_work_dir
results_root_dir: results_root
schedule_svc: 192.168.16.151:51131
